apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "12"
    labels:
      app: comprasnet-crawler-h
    name: comprasnet-crawler-h-deployment
    namespace: cgsis-h-php1-comprasnet-crawler
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      matchLabels:
        app: comprasnet-crawler-h
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        annotations:
          team: CGSIS/PHP1
        labels:
          app: comprasnet-crawler-h
      spec:
        containers:
        - env:
          - name: app_name
            valueFrom:
              secretKeyRef:
                key: app_name
                name: comprasnet-crawler-secret
          - name: app_env
            valueFrom:
              secretKeyRef:
                key: app_env
                name: comprasnet-crawler-secret
          - name: app_debug
            valueFrom:
              secretKeyRef:
                key: app_debug
                name: comprasnet-crawler-secret
          - name: app_url
            valueFrom:
              secretKeyRef:
                key: app_url
                name: comprasnet-crawler-secret
          - name: db_connection
            valueFrom:
              secretKeyRef:
                key: db_connection
                name: comprasnet-crawler-secret
          - name: db_host
            valueFrom:
              secretKeyRef:
                key: db_host
                name: comprasnet-crawler-secret
          - name: db_port
            valueFrom:
              secretKeyRef:
                key: db_port
                name: comprasnet-crawler-secret
          - name: db_database
            valueFrom:
              secretKeyRef:
                key: db_database
                name: comprasnet-crawler-secret
          - name: db_username
            valueFrom:
              secretKeyRef:
                key: db_username
                name: comprasnet-crawler-secret
          - name: db_password
            valueFrom:
              secretKeyRef:
                key: db_password
                name: comprasnet-crawler-secret
          - name: mail_mailer
            valueFrom:
              secretKeyRef:
                key: mail_mailer
                name: comprasnet-crawler-secret
          - name: mail_host
            valueFrom:
              secretKeyRef:
                key: mail_host
                name: comprasnet-crawler-secret
          - name: mail_port
            valueFrom:
              secretKeyRef:
                key: mail_port
                name: comprasnet-crawler-secret
          - name: mail_username
            valueFrom:
              secretKeyRef:
                key: mail_username
                name: comprasnet-crawler-secret
          - name: mail_password
            valueFrom:
              secretKeyRef:
                key: mail_password
                name: comprasnet-crawler-secret
          - name: mail_encryption
            valueFrom:
              secretKeyRef:
                key: mail_encryption
                name: comprasnet-crawler-secret
          - name: mail_from_address
            valueFrom:
              secretKeyRef:
                key: mail_from_address
                name: comprasnet-crawler-secret
          - name: comprasnet_base_url
            valueFrom:
              secretKeyRef:
                key: comprasnet_base_url
                name: comprasnet-crawler-secret
          - name: comprasnet_codigo_orgao
            valueFrom:
              secretKeyRef:
                key: comprasnet_codigo_orgao
                name: comprasnet-crawler-secret
          - name: comprasnet_codigo_ug
            valueFrom:
              secretKeyRef:
                key: comprasnet_codigo_ug
                name: comprasnet-crawler-secret
          - name: comprasnet_adm_emails
            valueFrom:
              secretKeyRef:
                key: comprasnet_adm_emails
                name: comprasnet-crawler-secret
          - name: comprasnet_support_emails
            valueFrom:
              secretKeyRef:
                key: comprasnet_support_emails
                name: comprasnet-crawler-secret
          - name: comprasnet_usuario_sistema
            valueFrom:
              secretKeyRef:
                key: comprasnet_usuario_sistema
                name: comprasnet-crawler-secret
          - name: comprasnet_senha_usuario
            valueFrom:
              secretKeyRef:
                key: comprasnet_senha_usuario
                name: comprasnet-crawler-secret
          image: sdh-k8s2-registry.cgu.gov.br/comprasnet-crawler-h:12.20221027172355
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /monitoramento/status
              port: web-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: comprasnet-crawler-h
          ports:
          - containerPort: 8080
            name: web-port
            protocol: TCP
          readinessProbe:
            failureThreshold: 18
            httpGet:
              path: /monitoramento/status
              port: web-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 75m
              memory: 512Mi
            requests:
              cpu: 75m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-09-06T01:09:16Z"
      lastUpdateTime: "2022-09-06T01:09:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-10-31T19:21:47Z"
      lastUpdateTime: "2022-10-31T19:21:47Z"
      message: 'pods "comprasnet-crawler-h-deployment-65979649ff-x7b6p" is forbidden:
        exceeded quota: quota-cgsis-h-php1-comprasnet-crawler, requested: limits.memory=512Mi,requests.memory=512Mi,
        used: limits.memory=1Gi,requests.memory=1Gi, limited: limits.memory=1Gi,requests.memory=1Gi'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    - lastTransitionTime: "2022-10-31T19:07:46Z"
      lastUpdateTime: "2022-10-31T19:21:47Z"
      message: ReplicaSet "comprasnet-crawler-h-deployment-65979649ff" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 26
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 1
kind: List
metadata:
  resourceVersion: ""
