apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3","kubernetes.io/change-cause":"2022-11-01 09:48:10 / Deploy via Jenkins (RollingUpdate) / Atualizado para comprasnet-crawler-p:1.20221101094516","team":"CGSIS/PHP1"},"creationTimestamp":"2022-09-20T14:27:59Z","generation":7,"labels":{"app":"comprasnet-crawler-p"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:team":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:app":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:team":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"comprasnet-crawler-p\"}":{".":{},"f:imagePullPolicy":{},"f:livenessProbe":{".":{},"f:failureThreshold":{},"f:httpGet":{".":{},"f:path":{},"f:port":{},"f:scheme":{}},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8080,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:name":{},"f:protocol":{}}},"f:readinessProbe":{".":{},"f:failureThreshold":{},"f:httpGet":{".":{},"f:path":{},"f:port":{},"f:scheme":{}},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:imagePullSecrets":{".":{},"k:{\"name\":\"regcred\"}":{".":{},"f:name":{}}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2022-09-20T14:27:59Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:kubernetes.io/change-cause":{}}},"f:spec":{"f:template":{"f:spec":{"f:containers":{"k:{\"name\":\"comprasnet-crawler-p\"}":{"f:image":{}}}}}}},"manager":"kubectl","operation":"Update","time":"2022-11-01T12:48:09Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:replicas":{},"f:template":{"f:spec":{"f:containers":{"k:{\"name\":\"comprasnet-crawler-p\"}":{"f:env":{".":{},"k:{\"name\":\"app_debug\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"app_env\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"app_name\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"app_url\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_adm_emails\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_base_url\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_codigo_orgao\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_codigo_ug\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_senha_usuario\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_support_emails\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"comprasnet_usuario_sistema\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"db_connection\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"db_database\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"db_host\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"db_password\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"db_port\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"db_username\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_encryption\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_from_address\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_host\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_mailer\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_password\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_port\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}},"k:{\"name\":\"mail_username\"}":{".":{},"f:name":{},"f:valueFrom":{".":{},"f:secretKeyRef":{".":{},"f:key":{},"f:name":{}}}}}}}}}}},"manager":"kubectl-edit","operation":"Update","time":"2022-11-01T13:02:03Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-11-01T13:03:59Z"}],"name":"comprasnet-crawler-p-deployment","namespace":"cgsis-p-php1-comprasnet-crawler","resourceVersion":"467731505","selfLink":"/apis/apps/v1/namespaces/cgsis-p-php1-comprasnet-crawler/deployments/comprasnet-crawler-p-deployment","uid":"c8d58b8b-67bf-40c9-aee9-47e0c984eb6d"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":3,"selector":{"matchLabels":{"app":"comprasnet-crawler-p"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"team":"CGSIS/PHP1"},"creationTimestamp":null,"labels":{"app":"comprasnet-crawler-p"}},"spec":{"containers":[{"env":[{"name":"app_name","valueFrom":{"secretKeyRef":{"key":"app_name","name":"comprasnet-crawler-secret"}}},{"name":"app_env","valueFrom":{"secretKeyRef":{"key":"app_env","name":"comprasnet-crawler-secret"}}},{"name":"app_debug","valueFrom":{"secretKeyRef":{"key":"app_debug","name":"comprasnet-crawler-secret"}}},{"name":"app_url","valueFrom":{"secretKeyRef":{"key":"app_url","name":"comprasnet-crawler-secret"}}},{"name":"db_connection","valueFrom":{"secretKeyRef":{"key":"db_connection","name":"comprasnet-crawler-secret"}}},{"name":"db_host","valueFrom":{"secretKeyRef":{"key":"db_host","name":"comprasnet-crawler-secret"}}},{"name":"db_port","valueFrom":{"secretKeyRef":{"key":"db_port","name":"comprasnet-crawler-secret"}}},{"name":"db_database","valueFrom":{"secretKeyRef":{"key":"db_database","name":"comprasnet-crawler-secret"}}},{"name":"db_username","valueFrom":{"secretKeyRef":{"key":"db_username","name":"comprasnet-crawler-secret"}}},{"name":"db_password","valueFrom":{"secretKeyRef":{"key":"db_password","name":"comprasnet-crawler-secret"}}},{"name":"mail_mailer","valueFrom":{"secretKeyRef":{"key":"mail_mailer","name":"comprasnet-crawler-secret"}}},{"name":"mail_host","valueFrom":{"secretKeyRef":{"key":"mail_host","name":"comprasnet-crawler-secret"}}},{"name":"mail_port","valueFrom":{"secretKeyRef":{"key":"mail_port","name":"comprasnet-crawler-secret"}}},{"name":"mail_username","valueFrom":{"secretKeyRef":{"key":"mail_username","name":"comprasnet-crawler-secret"}}},{"name":"mail_password","valueFrom":{"secretKeyRef":{"key":"mail_password","name":"comprasnet-crawler-secret"}}},{"name":"mail_encryption","valueFrom":{"secretKeyRef":{"key":"mail_encryption","name":"comprasnet-crawler-secret"}}},{"name":"mail_from_address","valueFrom":{"secretKeyRef":{"key":"mail_from_address","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_base_url","valueFrom":{"secretKeyRef":{"key":"comprasnet_base_url","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_codigo_orgao","valueFrom":{"secretKeyRef":{"key":"comprasnet_codigo_orgao","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_codigo_ug","valueFrom":{"secretKeyRef":{"key":"comprasnet_codigo_ug","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_adm_emails","valueFrom":{"secretKeyRef":{"key":"comprasnet_adm_emails","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_support_emails","valueFrom":{"secretKeyRef":{"key":"comprasnet_support_emails","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_usuario_sistema","valueFrom":{"secretKeyRef":{"key":"comprasnet_usuario_sistema","name":"comprasnet-crawler-secret"}}},{"name":"comprasnet_senha_usuario","valueFrom":{"secretKeyRef":{"key":"comprasnet_senha_usuario","name":"comprasnet-crawler-secret"}}}],"image":"sdp-k8s2-registry.cgu.gov.br/comprasnet-crawler-p:1.20221101094516","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":6,"httpGet":{"path":"/monitoramento/status","port":"web-port","scheme":"HTTP"},"initialDelaySeconds":360,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":10},"name":"comprasnet-crawler-p","ports":[{"containerPort":8080,"name":"web-port","protocol":"TCP"}],"readinessProbe":{"failureThreshold":18,"httpGet":{"path":"/monitoramento/status","port":"web-port","scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":10},"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"1","memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-11-01T13:03:59Z","lastUpdateTime":"2022-11-01T13:03:59Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-09-20T14:27:59Z","lastUpdateTime":"2022-11-01T13:03:59Z","message":"ReplicaSet \"comprasnet-crawler-p-deployment-5d856479dd\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":7,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
      kubernetes.io/change-cause: 2022-11-01 10:29:33 / Deploy via Jenkins (RollingUpdate)
        / Atualizado para comprasnet-crawler-p:2.20221101102818
      team: CGSIS/PHP1
    creationTimestamp: "2022-09-20T14:27:59Z"
    generation: 10
    labels:
      app: comprasnet-crawler-p
    name: comprasnet-crawler-p-deployment
    namespace: cgsis-p-php1-comprasnet-crawler
    resourceVersion: "467740782"
    selfLink: /apis/apps/v1/namespaces/cgsis-p-php1-comprasnet-crawler/deployments/comprasnet-crawler-p-deployment
    uid: c8d58b8b-67bf-40c9-aee9-47e0c984eb6d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      matchLabels:
        app: comprasnet-crawler-p
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        annotations:
          team: CGSIS/PHP1
        creationTimestamp: null
        labels:
          app: comprasnet-crawler-p
      spec:
        containers:
        - env:
          - name: app_name
            valueFrom:
              secretKeyRef:
                key: app_name
                name: comprasnet-crawler-secret
          - name: app_env
            valueFrom:
              secretKeyRef:
                key: app_env
                name: comprasnet-crawler-secret
          - name: app_debug
            valueFrom:
              secretKeyRef:
                key: app_debug
                name: comprasnet-crawler-secret
          - name: app_url
            valueFrom:
              secretKeyRef:
                key: app_url
                name: comprasnet-crawler-secret
          - name: db_connection
            valueFrom:
              secretKeyRef:
                key: db_connection
                name: comprasnet-crawler-secret
          - name: db_host
            valueFrom:
              secretKeyRef:
                key: db_host
                name: comprasnet-crawler-secret
          - name: db_port
            valueFrom:
              secretKeyRef:
                key: db_port
                name: comprasnet-crawler-secret
          - name: db_database
            valueFrom:
              secretKeyRef:
                key: db_database
                name: comprasnet-crawler-secret
          - name: db_username
            valueFrom:
              secretKeyRef:
                key: db_username
                name: comprasnet-crawler-secret
          - name: db_password
            valueFrom:
              secretKeyRef:
                key: db_password
                name: comprasnet-crawler-secret
          - name: mail_mailer
            valueFrom:
              secretKeyRef:
                key: mail_mailer
                name: comprasnet-crawler-secret
          - name: mail_host
            valueFrom:
              secretKeyRef:
                key: mail_host
                name: comprasnet-crawler-secret
          - name: mail_port
            valueFrom:
              secretKeyRef:
                key: mail_port
                name: comprasnet-crawler-secret
          - name: mail_username
            valueFrom:
              secretKeyRef:
                key: mail_username
                name: comprasnet-crawler-secret
          - name: mail_password
            valueFrom:
              secretKeyRef:
                key: mail_password
                name: comprasnet-crawler-secret
          - name: mail_encryption
            valueFrom:
              secretKeyRef:
                key: mail_encryption
                name: comprasnet-crawler-secret
          - name: mail_from_address
            valueFrom:
              secretKeyRef:
                key: mail_from_address
                name: comprasnet-crawler-secret
          - name: comprasnet_base_url
            valueFrom:
              secretKeyRef:
                key: comprasnet_base_url
                name: comprasnet-crawler-secret
          - name: comprasnet_codigo_orgao
            valueFrom:
              secretKeyRef:
                key: comprasnet_codigo_orgao
                name: comprasnet-crawler-secret
          - name: comprasnet_codigo_ug
            valueFrom:
              secretKeyRef:
                key: comprasnet_codigo_ug
                name: comprasnet-crawler-secret
          - name: comprasnet_adm_emails
            valueFrom:
              secretKeyRef:
                key: comprasnet_adm_emails
                name: comprasnet-crawler-secret
          - name: comprasnet_support_emails
            valueFrom:
              secretKeyRef:
                key: comprasnet_support_emails
                name: comprasnet-crawler-secret
          - name: comprasnet_usuario_sistema
            valueFrom:
              secretKeyRef:
                key: comprasnet_usuario_sistema
                name: comprasnet-crawler-secret
          - name: comprasnet_senha_usuario
            valueFrom:
              secretKeyRef:
                key: comprasnet_senha_usuario
                name: comprasnet-crawler-secret
          image: sdp-k8s2-registry.cgu.gov.br/comprasnet-crawler-p:2.20221101102818
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /monitoramento/status
              port: web-port
              scheme: HTTP
            initialDelaySeconds: 360
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: comprasnet-crawler-p
          ports:
          - containerPort: 8080
            name: web-port
            protocol: TCP
          readinessProbe:
            failureThreshold: 18
            httpGet:
              path: /monitoramento/status
              port: web-port
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-11-01T13:03:59Z"
      lastUpdateTime: "2022-11-01T13:03:59Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-11-01T13:29:33Z"
      lastUpdateTime: "2022-11-01T13:29:33Z"
      message: 'pods "comprasnet-crawler-p-deployment-96fc7884b-x28ml" is forbidden:
        exceeded quota: quota-cgsis-p-php1-comprasnet-crawler, requested: limits.cpu=1,limits.memory=1Gi,requests.cpu=1,requests.memory=1Gi,
        used: limits.cpu=1,limits.memory=1Gi,requests.cpu=1,requests.memory=1Gi, limited:
        limits.cpu=1,limits.memory=1Gi,requests.cpu=1,requests.memory=1Gi'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    - lastTransitionTime: "2022-11-01T13:39:34Z"
      lastUpdateTime: "2022-11-01T13:39:34Z"
      message: ReplicaSet "comprasnet-crawler-p-deployment-96fc7884b" has timed out
        progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 10
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 1
kind: List
metadata:
  resourceVersion: ""
